### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by zischwartz** [oreillymedia/thebe#1]
- [x] Add a cookie - prevent reloading the page from creating another container
- [x] Have it insert necessary stylesheets: jquery-ui, codemirror etc
- [x] Status bar
- [x] Smoother loading experience
- [x] Remove `tabindex` from cells
- [x] Just pass in a config in `<script>` tag
- [x] Only start docker container when someone clicks _run_ initially #4
- [x] Minimal Default Styles
- [x] Dev/example/gh-pages styles
- [x] A method to restart the kernel
- [x] A method to interrupt the kernel
- [x] How to package it up
- [ ] Selecting new kernels
- [x] A way to not use tempnb, and just run a notebook locally
- [ ] Figure out how best to put it in the [prototype](http://styleguide.oreilly.com/templates/content.html)
- [ ] Doesn't work in Safari, CORS header thing, proxy
- [x] Make it work by just including the `main-built.js` anywhere (i.e. no other files expected on your server)

**Comment by odewahn** [comment]
Also consider:
- [x] Only start a Docker container when the user clicks a run button, not on every page load
- [ ] How to get it into the prototype app
- [ ] ability in the UI to change to a different container (i.e., something running on boot2docker, or google cloud, or whatever)
